export enum ControlChangeMessageType {
    BankSelect = 0,
    ModulationWheel = 1,
    BreathController = 2,
    FootPedal= 4,
    PortamentoGlideTime = 5,
    DataEntryMSB = 6,
    MIDIVolume = 7,
    StreamBalance = 8,
    PanPositionBalance = 10,
    ExpressionPedal = 11,
    EffectController1 = 12,
    EffectController2 = 13,
    SliderKnobRibbonController1 = 16,
    SliderKnobRibbonController2 = 17,
    SliderKnobRibbonController3 = 18,
    SliderKnobRibbonController4 = 19,
    BankSelectLSB = 32,
    ModulationWheelLSB = 33,
    BreathControllerLSB = 34,
    FootPedalLSB = 36,
    PortamentoGlideTimeLSB = 37,
    DataEntryLSB = 38,
    VolumeLSB = 39,
    BalanceLSB = 40,
    PanPositionLSB = 42,
    ExpressionLSB = 43,
    EffectControl1LSB = 44,
    EffectControl2LSB = 45,
    SustainPedalOnOff = 64,
    PortamentoGlideOnOffSwitch = 65,
    SostenutoOnOffSwitch = 66,
    SoftPedalOnOffSwitch = 67,
    LegatoOnOffSwitch = 68,
    HoldPedal2 = 69,
    SoundController1 = 70,
    SoundController2 = 71,
    SoundController3 = 72,
    SoundController4 = 73,
    SoundController5 = 74,
    SoundController6 = 75,
    SoundController7 = 76,
    SoundController8 = 77,
    SoundController9 = 78,
    SoundController10 = 79,
    GeneralPurposeMIDICCController1 = 80,
    GeneralPurposeMIDICCController2 = 81,
    GeneralPurposeMIDICCController3 = 82,
    GeneralPurposeMIDICCController4 = 83,
    PortamentoCCControl = 84,
    HighResolutionVelocityPrefix = 88,
    Effect1Depth = 91,
    Effect2Depth = 92,
    Effect3Depth = 93,
    Effect4Depth = 94,
    Effect5Depth = 95,
    DataBoundIncrement  = 96,
    DataBoundDecrement = 97,
    NonRegisteredParameterNumberLSB = 98,
    NonRegisteredParameterNumberMSB = 99,
    RegisteredParameterNumberLSB = 100,
    RegisteredParameterNumberMSB = 101,
    AllSoundOff = 120,
    ResetAllControllers = 121,
    LocalOnOffSwitch = 122,
    AllNotesOff = 123,
    OmniModeOff = 124,
    OmniModeOn = 125,
    MonoMode = 126,
    PolyMode = 127,
    Undefined = -1
}

export function getControlChangeMessage(ccNumber: number): ControlChangeMessageTypeData {
    const controlChangeMessage: ControlChangeMessageTypeData = MIDIControlChangeTypeLookup[ccNumber];
    return controlChangeMessage || MIDIControlChangeTypeLookup[ControlChangeMessageType.Undefined];
}

export type ControlChangeMessageTypeData = {
    type: ControlChangeMessageType;
    name: string,
    description: string;
};

const MIDIControlChangeTypeLookup: Record<number, ControlChangeMessageTypeData> = {
    [ControlChangeMessageType.BankSelect]: { type: ControlChangeMessageType.BankSelect, name: "Bank Select", description: "Switch Preset Banks for Patch Selection. This is used in combination with program change commands" },
    [ControlChangeMessageType.ModulationWheel]: { type: ControlChangeMessageType.ModulationWheel, name: "Modulation Wheel", description: "The Mod Wheel is one of the most used CC messages. It can be assigned to a variety of different controls in your synthesizer/sampler/effects units. Common mappings include adding vibrato, or adjusting filter cutoff"},
    [ControlChangeMessageType.BreathController]: { type: ControlChangeMessageType.BreathController, name: "Breath Controller", description: "Like the Mod Wheel, this CC is intended for real time performance modulation. The CC2 Breath controller was originally defined for electronic wind instrument breath amount"},
    [ControlChangeMessageType.FootPedal]: { type: ControlChangeMessageType.FootPedal, name: "Foot Pedal", description: "The Foot Controller CC4 can be used like an extra expression pedal, for real time performance modulation"},
    [ControlChangeMessageType.PortamentoGlideTime]: { type: ControlChangeMessageType.PortamentoGlideTime, name: "Portamento/Glide Time", description: "The Portamento/Glide defines how consecutive note pitches are interpolated between. With no portamento/glide, the pitch of a new key press is immediate and in tune to the key. With portamento/glide, the frequency is glided up/down from the previous frequency"},
    [ControlChangeMessageType.DataEntryMSB]: { type: ControlChangeMessageType.DataEntryMSB, name: "Data Entry (MSB)", description: "This CC is used with SYSEX NRPN or RPN messages"},
    [ControlChangeMessageType.MIDIVolume]: { type: ControlChangeMessageType.MIDIVolume, name: "MIDI Volume", description: "The MIDI Volume CC7 is used to control the overall volume of the instrument - the output volume"},
    [ControlChangeMessageType.StreamBalance]: { type: ControlChangeMessageType.StreamBalance, name: "Stereo Balance", description: "The Stereo Panning CC8 is used to control the Left/Right balance for instruments with stereo signal paths. Note: CC10 is often used instead to control panning"},
    [ControlChangeMessageType.PanPositionBalance]: { type: ControlChangeMessageType.PanPositionBalance, name: "Pan Position / Balance", description: "The Mono Panning CC10 is used to control the Left/Right balance for instruments with stereo signal output. Note: CC8 is occasionally used instead to control panning"},
    [ControlChangeMessageType.ExpressionPedal]: { type: ControlChangeMessageType.ExpressionPedal, name: "Expression Pedal", description: "The Expression Pedal CC11 is one of the most common used CCs for live performance modulation. It is usually assigned within the instrument to control a variety of different modulation options"},
    [ControlChangeMessageType.EffectController1]: { type: ControlChangeMessageType.EffectController1, name: "Effect Controller 1", description: "This Effect Controller CC12 is intended for controlling effects parameters within an instrument"},
    [ControlChangeMessageType.EffectController2]: { type: ControlChangeMessageType.EffectController1, name: "Effect Controller 2", description: "This Effect Controller CC13 is intended for controlling effects parameters within an instrument"},
    [ControlChangeMessageType.SliderKnobRibbonController1]: { type: ControlChangeMessageType.SliderKnobRibbonController1, name: "Slider, Knob or Ribbon Controller 1", description: "The CC16 is a general purpose MIDI controller that can be used for performance modulation"},
    [ControlChangeMessageType.SliderKnobRibbonController2]: { type: ControlChangeMessageType.SliderKnobRibbonController2, name: "Slider, Knob or Ribbon Controller 2", description: "The CC17 is a general purpose MIDI controller that can be used for performance modulation"},
    [ControlChangeMessageType.SliderKnobRibbonController3]: { type: ControlChangeMessageType.SliderKnobRibbonController3, name: "Slider, Knob or Ribbon Controller 3", description: "The CC18 is a general purpose MIDI controller that can be used for performance modulation"},
    [ControlChangeMessageType.SliderKnobRibbonController4]: { type: ControlChangeMessageType.SliderKnobRibbonController4, name: "Slider, Knob or Ribbon Controller 4", description: "The CC19 is a general purpose MIDI controller that can be used for performance modulation"},
    [ControlChangeMessageType.BankSelectLSB]: { type: ControlChangeMessageType.BankSelectLSB, name: "Bank Select (LSB)", description: "This is used in conjunction with CC0 Bank Select for some instruments with additional mod resolution"},
    [ControlChangeMessageType.ModulationWheelLSB]: { type: ControlChangeMessageType.ModulationWheelLSB, name: "Modulation Wheel (LSB)", description: "This is used in conjunction with CC1 Mod Wheel for some instruments with additional mod resolution."},
    [ControlChangeMessageType.BreathControllerLSB]: { type: ControlChangeMessageType.BreathControllerLSB, name: "Modulation Wheel (LSB)", description: "This is used in conjunction with CC2 Breath for some instruments with additional mod resolution"},
    [ControlChangeMessageType.FootPedalLSB]: { type: ControlChangeMessageType.FootPedalLSB, name: "Foot Pedal (LSB)", description: "This is used in conjunction with CC4 Foot Pedal for some instruments with additional mod resolution"},
    [ControlChangeMessageType.PortamentoGlideTimeLSB]: { type: ControlChangeMessageType.PortamentoGlideTimeLSB, name: "Portamento/Glide Time (LSB)", description: "This is used in conjunction with CC5 Portamento/Glide Time for some instruments with additional mod resolution"},
    [ControlChangeMessageType.DataEntryLSB]: { type: ControlChangeMessageType.DataEntryLSB, name: "Data Entry (LSB)", description: "This CC is used with SYSEX NRPN or RPN messages"},
    [ControlChangeMessageType.VolumeLSB]: { type: ControlChangeMessageType.VolumeLSB, name: "Volume (LSB)", description: "This is used in conjunction with CC7 Volume for some instruments with additional mod resolution"},
    [ControlChangeMessageType.BalanceLSB]: { type: ControlChangeMessageType.BalanceLSB, name: "Balance (LSB)", description: "This is used in conjunction with CC8 Stereo Balance for some instruments with additional mod resolution"},
    [ControlChangeMessageType.PanPositionLSB]: { type: ControlChangeMessageType.PanPositionLSB, name: "Pan Position (LSB)", description: "This is used in conjunction with CC10 Pan Position for some instruments with additional mod resolution"},
    [ControlChangeMessageType.ExpressionLSB]: { type: ControlChangeMessageType.ExpressionLSB, name: "Expression (LSB)", description: "This is used in conjunction with CC11 Expression for some instruments with additional mod resolution"},
    [ControlChangeMessageType.EffectControl1LSB]: { type: ControlChangeMessageType.EffectControl1LSB, name: "Expression (LSB)", description: "This is used in conjunction with CC12 Effect Controller 1 for some instruments with additional mod resolution"},
    [ControlChangeMessageType.EffectControl2LSB]: { type: ControlChangeMessageType.EffectControl2LSB, name: "Expression (LSB)", description: "This is used in conjunction with CC12 Effect Controller 2 for some instruments with additional mod resolution"},
    [ControlChangeMessageType.SustainPedalOnOff]: { type: ControlChangeMessageType.SustainPedalOnOff, name: "Sustain Pedal On/Off", description: "The Sustain Pedal CC64 is one of the most common MIDI CC messages, used to hold played notes while the sustain pedal is active/depressed. Values of 0-63 indicate OFF. Values 26-127 indicate ON"},
    [ControlChangeMessageType.PortamentoGlideOnOffSwitch]: { type: ControlChangeMessageType.PortamentoGlideOnOffSwitch, name: "Portamento/Glide On/Off Switch", description: "This CC65 is intended to be used as an on/off switch for Portamento/Glide. Values of 0-63 indicate OFF. Values 26-127 indicate ON."},
    [ControlChangeMessageType.SostenutoOnOffSwitch]: { type: ControlChangeMessageType.SostenutoOnOffSwitch, name: "Sostenuto On/Off Switch", description: "This Sostenuto CC64 is intended to activate the sustain of only the active notes when the pedal is first engaged. Values of 0-63 indicate OFF. Values 26-127 indicate ON"},
    [ControlChangeMessageType.SoftPedalOnOffSwitch]: { type: ControlChangeMessageType.SoftPedalOnOffSwitch, name: "Soft Pedal On/Off Switch", description: "The Soft Pedal CC67 is a switch to activate the soft strike effect. Most pianos have three strings that are struck by a hammer, but the hammer or keys are shifted so only two strings are struck with a key strike. Values of 0-63 indicate OFF. Values 26-127 indicate ON"},
    [ControlChangeMessageType.LegatoOnOffSwitch]: { type: ControlChangeMessageType.LegatoOnOffSwitch, name: "Legato On/Off Switch", description: "The Legato CC68 is a switch to enable or disable Legato / Smooth transitions between consecutive notes. Values of 0-63 indicate OFF. Values 26-127 indicate ON"},
    [ControlChangeMessageType.HoldPedal2]: { type: ControlChangeMessageType.HoldPedal2, name: "Legato On/Off Switch", description: "The Hold Pedal CC69 is an alternative control message to Sustain that controls how notes are held and fade out. Values of 0-63 indicate OFF. Values 26-127 indicate ON"},
    [ControlChangeMessageType.SoundController1]: { type: ControlChangeMessageType.SoundController1, name: "Sound Controller 1 (Sound Variation)", description: "Sound Controller CC70 is often assigned to sound generation variance."},
    [ControlChangeMessageType.SoundController2]: { type: ControlChangeMessageType.SoundController2, name: "Sound Controller 2 (Filter Resonance)", description: "Sound Controller CC71 is often assigned to filter resonance amount / Q amount"},
    [ControlChangeMessageType.SoundController3]: { type: ControlChangeMessageType.SoundController3, name: "Sound Controller 3 (Amp Envelope Decay)", description: "Sound Controller CC72 is often assigned to the amp envelope release time. It may affect how notes are held and fade out"},
    [ControlChangeMessageType.SoundController4]: { type: ControlChangeMessageType.SoundController4, name: "Sound Controller 4 (Amp Envelope Attack)", description: "Sound Controller CC73 is often assigned to the amp envelope attack time. This is the amount of time from key strike to maximum volume"},
    [ControlChangeMessageType.SoundController5]: { type: ControlChangeMessageType.SoundController5, name: "Sound Controller 5 (Filter Cutoff)", description: "Sound Controller CC74 is often assigned to filter cutoff point / Q location, at some frequency/hertz"},
    [ControlChangeMessageType.SoundController6]: { type: ControlChangeMessageType.SoundController6, name: "Sound Controller 6", description: "CC75 is a general purpose CC for altering some sound generation"},
    [ControlChangeMessageType.SoundController7]: { type: ControlChangeMessageType.SoundController7, name: "Sound Controller 7", description: "CC76 is a general purpose CC for altering some sound generation"},
    [ControlChangeMessageType.SoundController8]: { type: ControlChangeMessageType.SoundController8, name: "Sound Controller 8", description: "CC77 is a general purpose CC for altering some sound generation, filtering or effect"},
    [ControlChangeMessageType.SoundController9]: { type: ControlChangeMessageType.SoundController9, name: "Sound Controller 9", description: "CC78 is a general purpose CC for altering some sound generation, filtering or effect"},
    [ControlChangeMessageType.SoundController10]: { type: ControlChangeMessageType.SoundController10, name: "Sound Controller 10", description: "CC79 is a general purpose CC for altering some sound generation, filtering or effect"},
    [ControlChangeMessageType.GeneralPurposeMIDICCController1]: { type: ControlChangeMessageType.GeneralPurposeMIDICCController1, name: "General Purpose MIDI CC Controller 1", description: "General Purpose CC Switch CC80. Values of 0-63 indicate OFF. Values 26-127 indicate ON"},
    [ControlChangeMessageType.GeneralPurposeMIDICCController2]: { type: ControlChangeMessageType.GeneralPurposeMIDICCController2, name: "General Purpose MIDI CC Controller 2", description: "General Purpose CC Switch CC81. Values of 0-63 indicate OFF. Values 26-127 indicate ON"},
    [ControlChangeMessageType.GeneralPurposeMIDICCController3]: { type: ControlChangeMessageType.GeneralPurposeMIDICCController3, name: "General Purpose MIDI CC Controller 3", description: "General Purpose CC Switch CC82. Values of 0-63 indicate OFF. Values 26-127 indicate ON"},
    [ControlChangeMessageType.GeneralPurposeMIDICCController4]: { type: ControlChangeMessageType.GeneralPurposeMIDICCController4, name: "General Purpose MIDI CC Controller 4", description: "General Purpose CC Switch CC83. Values of 0-63 indicate OFF. Values 26-127 indicate ON"},
    [ControlChangeMessageType.PortamentoCCControl]: { type: ControlChangeMessageType.PortamentoCCControl, name: "Portamento CC Control", description: "CC84 Controls the amount of Portamento"},
    [ControlChangeMessageType.HighResolutionVelocityPrefix]: { type: ControlChangeMessageType.HighResolutionVelocityPrefix, name: "High Resolution Velocity Prefix", description: "CC88 Extends the range of possible velocity values"},
    [ControlChangeMessageType.Effect1Depth]: { type: ControlChangeMessageType.Effect1Depth, name: "Effect 1 Depth", description: "CC91 Usually controls reverb send amount"},
    [ControlChangeMessageType.Effect2Depth]: { type: ControlChangeMessageType.Effect2Depth, name: "Effect 2 Depth", description: "CC92 Usually controls tremolo amount"},
    [ControlChangeMessageType.Effect3Depth]: { type: ControlChangeMessageType.Effect3Depth, name: "Effect 3 Depth", description: "CC93 Usually controls chorus amount"},
    [ControlChangeMessageType.Effect4Depth]: { type: ControlChangeMessageType.Effect4Depth, name: "Effect 4 Depth", description: "CC94 Usually controls detune amount"},
    [ControlChangeMessageType.Effect5Depth]: { type: ControlChangeMessageType.Effect5Depth, name: "Effect 5 Depth", description: "CC95 Usually controls phaser amount"},
    [ControlChangeMessageType.DataBoundIncrement]: { type: ControlChangeMessageType.DataBoundIncrement, name: "Data Increment (+1)", description: "CC96 is usually used to increment data for RPN and NRPN messages"},
    [ControlChangeMessageType.DataBoundDecrement]: { type: ControlChangeMessageType.DataBoundDecrement, name: "Data Drecement (-1)", description: "CC97 is usually used to decrement data for RPN and NRPN messages"},
    [ControlChangeMessageType.NonRegisteredParameterNumberLSB]: { type: ControlChangeMessageType.NonRegisteredParameterNumberLSB, name: "Non-Registered Parameter Number LSB (NRPN)", description: "CC98 is for controllers 6, 38, 96, and 97, it selects the NRPN parameter."},
    [ControlChangeMessageType.NonRegisteredParameterNumberMSB]: { type: ControlChangeMessageType.NonRegisteredParameterNumberMSB, name: "Non-Registered Parameter Number MSB (NRPN)", description: "CC99 is for controllers 6, 38, 96, and 97, it selects the NRPN parameter."},
    [ControlChangeMessageType.RegisteredParameterNumberLSB]: { type: ControlChangeMessageType.RegisteredParameterNumberLSB, name: "Registered Parameter Number LSB (RPN)", description: "CC99 is for controllers 6, 38, 96, and 97, it selects the RPN parameter"},
    [ControlChangeMessageType.RegisteredParameterNumberMSB]: { type: ControlChangeMessageType.RegisteredParameterNumberMSB, name: "Registered Parameter Number MSB (RPN)", description: "CC100 is for controllers 6, 38, 96, and 97, it selects the RPN parameter"},
    [ControlChangeMessageType.AllSoundOff]: { type: ControlChangeMessageType.AllSoundOff, name: "All Sound Off", description: "CC120 Mutes all sound. It does so regardless of release time or sustain. (See MIDI CC 123)"},
    [ControlChangeMessageType.ResetAllControllers]: { type: ControlChangeMessageType.ResetAllControllers, name: "Reset All Controllers", description: "CC121 reset all controllers to their default"},
    [ControlChangeMessageType.LocalOnOffSwitch]: { type: ControlChangeMessageType.LocalOnOffSwitch, name: "Local on/off switch", description: "CC122 turns internal connection of a MIDI keyboard or workstation, etc. on or off. If you use a computer, you will most likely want local control off to avoid notes being played twice. Once locally and twice when the note is sent back from the computer to your keyboard."},
    [ControlChangeMessageType.AllNotesOff]: { type: ControlChangeMessageType.AllNotesOff, name: "All Notes Off", description: "CC123 Mutes all sounding notes. Release time will still be maintained, and notes held by sustain will not turn off until sustain pedal is depressed"},
    [ControlChangeMessageType.OmniModeOff]: { type: ControlChangeMessageType.OmniModeOff, name: "Omni Mode Off", description: "CC124 Sets 'Omni Off' mode"},
    [ControlChangeMessageType.OmniModeOn]: { type: ControlChangeMessageType.OmniModeOn, name: "Omni Mode On", description: "CC125 Sets 'Omni On' mode"},
    [ControlChangeMessageType.MonoMode]: { type: ControlChangeMessageType.MonoMode, name: "Mono Mode", description: "CC126 Sets device mode to Monophonic. The value equals the number of channels, or 0 if the number of channels equals the number of voices in the receiver"},
    [ControlChangeMessageType.PolyMode]: { type: ControlChangeMessageType.PolyMode, name: "Poly Mode", description: "CC127 Sets device mode to Polyphonic"},
    [ControlChangeMessageType.Undefined]: { type: ControlChangeMessageType.Undefined, name: "Undefined", description: "Undefined in the MIDI specification"},
};